version: "3.4"

networks:
  tibava:
    name: tibava_network

services:
    tibavafrontend:
        image: tibavafrontend
        networks:
          - tibava
        build:
          context: .
          dockerfile: ./Dockerfile
        ports:
          - 3000:3000
        volumes:
          - type: bind
            source: ./media
            target: /app/src/media
